require("colorbuddy").colorscheme("gruvbuddy")
require "options"
require "keymaps"
require "plugins"
require "plugin.completion"
require "plugin.rust"
require "plugin.comment"
require "plugin.luasnip"
require "plugin.lsp_signs"
require "plugin.telescope"
require "plugin.treesitter"
require "plugin.statusline"
require "plugin.lsp_status"
require "plugin.discord_presence"
require "plugin.nvim_tree"
require "plugin.buffer_line"
